# Generated by Django 3.1.4 on 2020-12-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='country')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='vat')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'By cash'), ('Card', 'By card')], default='Card', max_length=4, verbose_name='payment method'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.country', verbose_name='country of order'),
        ),
    ]
