# Generated by Django 3.1.4 on 2020-12-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201216_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='description'),
        ),
    ]
